services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      - CHROMA_SERVER=true
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/db:/app/db
    depends_on:
      - chromadb
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8000/api/v1
    depends_on:
      - backend
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./backend/chroma_db:/chroma/chroma/
